logging:
  file:
    #日志文件目录。./表示相对于项目根目录，即项目根目录下的logs目录。也可配置绝对路径，如：/home/webapp/logs
    path: ./logs

spring:
  cloud:
    config:
      server:
        git:
          # git仓库
          uri: https://gitee.com/jq_di/springcloud-template.git
          ##搜索目录.这个目录指的是github上的目录
          search-paths:
            - config-yml
          #username: 897665787@qq.com
          #password: ******
          # 强制拉取资源文件
          force-pull: true
          # 默认拉取的分支
          default-label: master
