template:
  domain: http://p-domain.com
  enable:
    cache: redis # guava:本地缓存,redis:redis缓存,combination:组合缓存
    lock: redisson # jvm:jvm锁,redisson:redisson分布式锁
    message-driven: rocketmq # springevent:spring事件,rabbitmq:RabbitMQ消息队列,rocketmq:RocketMQ消息队列,redis:redis消息队列
  sqllimit:
    max: 9999

# 数据库表字段加密
encrypt:
  enable: true
  key: pg5omd5kchlchco
  type: default
