logging:
  file:
    #日志文件目录。./表示相对于项目根目录，即项目根目录下的logs目录。也可配置绝对路径，如：/home/webapp/logs
    path: ./logs

template:
  domain: http://domain.com
  message-driven: rocketmq # springevent:spring事件,rabbitmq:RabbitMQ消息队列,rocketmq:RocketMQ消息队列,redis:redis消息队列

# 开发者路由配置
developer:
  enabled: false
  headers: x-deviceid,x-token
