# 消息驱动 配置
messagedriven:
  prefix: ${spring.application.name}
  framework:
    exchange:
      direct: ${messagedriven.prefix}-direct
      xdelayed: ${messagedriven.prefix}-x-delayed-direct
    queue:
      xdelayed:
        name: ${messagedriven.prefix}-x-delayed
        key: ${messagedriven.prefix}-key-x-delayed
      dead_letter:
        name: ${messagedriven.prefix}-x-dead-letter
        key: ${messagedriven.prefix}-key-x-dead-letter
      common:
        name: ${messagedriven.prefix}-common
        key: ${messagedriven.prefix}-key-common
  self:
    exchange:
      direct2: ${messagedriven.prefix}-direct2
    queue:
      xdelayed:
        name: ${messagedriven.prefix}-x-delayed
        key: ${messagedriven.prefix}-key-x-delayed
      dead_letter:
        name: ${messagedriven.prefix}-x-dead-letter
        key: ${messagedriven.prefix}-key-x-dead-letter
      common:
        name: ${messagedriven.prefix}-common
        key: ${messagedriven.prefix}-key-common
  # 广播消息
  fanout-prefix: fanout
  deploy:
    exchange: ${messagedriven.fanout-prefix}-deploy
  canal:
    exchange: ${messagedriven.fanout-prefix}-canal
    prefix: ${messagedriven.canal.exchange}
    queue: ${messagedriven.canal.prefix}-${spring.application.name}
  order_create:
    exchange: ${messagedriven.fanout-prefix}-order_create
    prefix: ${messagedriven.order_create.exchange}
    sms_queue: ${messagedriven.canal.prefix}-sms
    countmoney_queue: ${messagedriven.canal.prefix}-countmoney
