logging:
  file:
    #日志文件目录。./表示相对于项目根目录，即项目根目录下的logs目录。也可配置绝对路径，如：/home/webapp/logs
    path: ./logs/${spring.application.name}

template:
  domain: http://d-domain.com
  enable:
    cache: guava # guava:本地缓存,redis:redis缓存,combination:组合缓存,cachemanager:CacheManager缓存
    lock: jvm # jvm:jvm锁,redisson:redisson分布式锁
    message-driven: springevent # springevent:spring事件,rabbitmq:RabbitMQ消息队列,rocketmq:RocketMQ消息队列,redis:redis消息队列
  sqllimit:
    enable: true
    max: 9999

filestorage:
  active: local
  local:
    endpoint: /home/data/oss
    bucketName: buket-template
    domain: http://18.163.115.207:8020 # 访问域名，可以结合spring.resources.static-locations静态资源来使用 或 使用nginx配置访问目录指向
  minio:
    endpoint: http://127.0.0.1:9000
    accessKey: pRYo5fCm9ZyVNKLA
    secretKey: Lv5yFUrBOXrNsZJVZ93XxSVl7JiNA99J
    bucketName: buket-template-dev
    domain: http://127.0.0.1:9000/buket-template-dev # 访问域名，例如：“https://image.d-domain.com”
